# 指定のディレクトリやファイルではスペルチェックを無効にします
[files]
extend-exclude = [
  "*.svg",
  "node_modules",
  "vendor/**/*",
  "**/*.min.js",
  "logs/**/*"
]

# 指定の拡張子のファイルではスペルチェックを無効にします
[files.ignore]
binary = ["*.png", "*.jpg", "*.gif", "*.ico", "*.exe"]

# ビルドファイルのスペルチェックを無効にします
[build]
enabled = false
