# 指定のディレクトリやファイルではスペルチェックを無効にします
[files]
extend-exclude = [
  "*.svg",
  "node_modules",
  "vendor/**/*",
  "**/*.min.js",
  "logs/**/*",
  "*.png",
  "*.jpg",
  "*.gif",
  "*.ico",
  "*.exe"
]

# ビルドファイルのスペルチェックを無効にします
[build]
enabled = false
